/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SeminovosRouteImport } from './routes/seminovos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminovosRoute = SeminovosRouteImport.update({
  id: '/seminovos',
  path: '/seminovos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/produtos': typeof ProdutosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/seminovos': typeof SeminovosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/produtos': typeof ProdutosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/seminovos': typeof SeminovosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/produtos': typeof ProdutosRoute
  '/quem-somos': typeof QuemSomosRoute
  '/seminovos': typeof SeminovosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/noticias'
    | '/produtos'
    | '/quem-somos'
    | '/seminovos'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/noticias'
    | '/produtos'
    | '/quem-somos'
    | '/seminovos'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/noticias'
    | '/produtos'
    | '/quem-somos'
    | '/seminovos'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  NoticiasRoute: typeof NoticiasRoute
  ProdutosRoute: typeof ProdutosRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SeminovosRoute: typeof SeminovosRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminovos': {
      id: '/seminovos'
      path: '/seminovos'
      fullPath: '/seminovos'
      preLoaderRoute: typeof SeminovosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  NoticiasRoute: NoticiasRoute,
  ProdutosRoute: ProdutosRoute,
  QuemSomosRoute: QuemSomosRoute,
  SeminovosRoute: SeminovosRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
